# Make file from Hipe

# objects.
OBJS= main.o
# Objects from the hipe server which reside in the parent directory
# after running make generated by qmake in parent directory (refer
# README in parent dir).
HOBJS=
CC=g++
CFLAGS=-c
LFLAGS= #-lgtest -lgtest_main -lpthread
INC=

main: $(OBJS) 
	$(CC) $(OBJS) $(HOBJS) $(LFLAGS) $(INC) -o $@

build/%.o: %.cpp
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm main build/*.o *.o output.txt

ctags:
	myctags -R . /usr/include/gtest